### ISSUE TITLE
Does not work with yarn 0.28.1

### ISSUE THREAD

**Issue by scinos** [wmhilton/yarn-lockfile#1]
They don't publish yarn.lock parser anymore:

```
Error: Cannot find module 'yarn/lib/lockfile/parse.js'
```

```bash
$ ls node_modules/yarn/lib
v8-compile-cache.js  yarn-cli.js
```

**Comment by scinos** [comment]
Related: https://github.com/yarnpkg/yarn/issues/3879

**Comment by billiegoose** [comment]
Mother. Fucker.

Here's the entire contents of the npm tarball:
```
LICENSE
package.json
README.md

bin:
yarn*
yarn.cmd
yarn.js*
yarnpkg*
yarnpkg.cmd

lib:
v8-compile-cache.js
yarn-cli.js*
```

Everything in `bin` is a shim to `lib/yarn-cli.js`, which is bundled with Webpack, and doesn't export anything.

You can't even try to load it as a module - they added an `assert` so it crashes if there's no command line arguments being passed to it.

```
> yarn = require('./lib/yarn-cli.js')
AssertionError [ERR_ASSERTION]: false == true
    at Console.assert (console.js:165:23)
    at Object.<anonymous> (C:\Users\Will\Desktop\dist\lib\yarn-cli.js:69087:9)
    at __webpack_require__ (C:\Users\Will\Desktop\dist\lib\yarn-cli.js:21:30)
    at Object.<anonymous> (C:\Users\Will\Desktop\dist\lib\yarn-cli.js:129302:18)
    at __webpack_require__ (C:\Users\Will\Desktop\dist\lib\yarn-cli.js:21:30)
    at exports.__esModule (C:\Users\Will\Desktop\dist\lib\yarn-cli.js:67:18)
    at Object.<anonymous> (C:\Users\Will\Desktop\dist\lib\yarn-cli.js:70:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

The only solution I can think of would be to clone the source from Github, build it (because I'm sure it needs to be transpiled) and *then* try to load the parser. And I'm not sure I even want to jump through all those hoops.

**Comment by Daniel15** [comment]
Reaching into Yarn's internal APIs like that was never officially supported. The `lib` directory is an internal implementation detail and is not part of Yarn's public API, and could change at any moment (eg. refactoring could move some files around). The Yarn npm package now intentionally includes the combined JS file to improve consistency across all installation methods and to fix strange bugs with installing Yarn via npm (previously, all Yarn installation methods used the combined JS files, *except for* the npm package).

Your dependency of `"yarn": "*"` in `package.json` is risky, as a public API can change between major releases. The lockfile format in Yarn has not changed at all, so you could use an older version of Yarn (like `0.27.x`) indefinitely and it'll continue to work.

https://github.com/yarnpkg/yarn/issues/3879 is tracking this on the Yarn side. Most likely the lockfile parser will be published as a separate npm package.

> You can't even try to load it as a module - they added an `assert` so it crashes if there's no command line arguments being passed to it.

The assert has been there for a while: https://github.com/yarnpkg/yarn/blame/fa0fb69a567e1c44320d6f2a5f2a8ee42bc226ea/src/cli/index.js#L120

**Comment by billiegoose** [comment]
> Most likely the lockfile parser will be published as a separate npm package.

I would love to see that, but I haven't seen any evidence that yarn is moving in that direction. Frankly I foresee them ceasing publishing yarn to npm entirely, flipping the switch on their registry proxy, and announcing you can now publish directly to the yarn registry.

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by BYK** [comment]
There's also an upcoming change that will allow you to import `yarn-cli.js` file. Sincere apology for the inconvenience. That said this wouldn't change the `assert` issue mentioned above.

**Comment by BYK** [comment]
>I would love to see that, but I haven't seen any evidence that yarn is moving in that direction.

May be you're not looking hard enough: https://github.com/yarnpkg/yarn/issues/3879 😃 

>Frankly I foresee them ceasing publishing yarn to npm entirely, flipping the switch on their registry proxy, and announcing you can now publish directly to the yarn registry.

First of all, "them" is us. I mean @Daniel15 and I and some more people and we certainly don't have any plans like that. That said I'd be curious why would you think that way to address any issues with our communications.

Also if you'd like to work on that issue and help us release the lockfile parser as a spearate package, you're more than welcome!

**Comment by billiegoose** [comment]
> First of all, "them" is us.

Hello then! I stand partially corrected. When @Daniel15 initially linked to yarnpkg/yarn#3879 I saw it as a two-week old feature request somebody had made... It wasn't until much later I realized Daniel15 was a maintainer, at Facebook, in a position to actually carry out the idea.

> That said I'd be curious why would you think that way to address any issues with out communications.

Quite a while ago I concocted a conspiracy theory that yarn was an effort by Facebook to try to win influence over the dev community by undermining npm, inc. and creating a "better, safer alternative" that was under their tight control. Since then, I've probably fallen prone to confirmation bias, seeing only [evidence](https://twitter.com/wmhilton/status/889973527201402881) that [seems](https://twitter.com/wmhilton/status/853313980760281088) to [confirm](https://twitter.com/wmhilton/status/858169644552781824) my [suspicion](https://twitter.com/feross/status/878444879310856193). Although the [official statement](https://twitter.com/sebmck/status/878205844789252096) is there is no "illuminati conspiracy" 😉 I continue to play devil's advocate. Which probably sounds ridiculous to you if you work at Facebook. So... that's a long-winded explanation of why I would think that way... and I don't know if it's worth addressing communications or not... I think it's a pretty fringe opinion?

> Also if you'd like to work on that issue and help us release the lockfile parser as a spearate package, you're more than welcome!

If you can look past my weird paranoid baggage, then sure I'd be glad to help release the lockfile parser as its own package! I'd be even gladder if we could steer `yarn` back towards a JSON-based lockfile. Or at least come up with a name and official spec for the file format. Now that npm has a "competing" lockfile format, I'm genuinely worried that the yarn and npm ecosystems will start running into compatibility issues. I'm super into the idea of a hyper-converged isomorphic codebase that runs on any platform. (i.e. the idea of making all the JavaScript modules in the registry compatible with each other and capable of running in every environment that supports JavaScript) Lately, I've been playing with SystemJS (specifically the bundled version in [getlibs.com](http://getlibs.com/)) and it's an *amazing* developer experience. I'm convinced that dynamic module loading is the future of software development. It's the logical evolution of hot-module reloading: hot-module installation. You don't have to install anything - just write code and it works! Of course that would cause tremendous problems in production... which is why lockfile formats are *so important* to the future of the JS ecosystem as a whole. You can't run a piece of software if you can't install it, and you can't install it if you can't resolve its dependencies correctly, and you can't resolve its dependencies correctly if it uses a proprietary lockfile format that is only understood by one tool. Yarn doesn't work in the browser (although neither do npm or pnpm) or with Node alternatives like [dukboot](https://gitlab.com/dukboot/dukboot) and the very first step to work around that is to at least be able to parse the lockfile.

**Comment by Daniel15** [comment]
> It wasn't until much later I realized Daniel15 was a maintainer, at Facebook, in a position to actually carry out the idea.

Yarn is a community project 😃 Anyone can contribute to it, even if they're not Facebook employees. Many of the core contributors are not Facebook employees.

> Quite a while ago I concocted a conspiracy theory that yarn was an effort by Facebook to try to win influence over the dev community by undermining npm, inc. and creating a "better, safer alternative" that was under their tight control. 

This is absolutely not true. All the Yarn developers are just regular developers like you and me, just working on things that we enjoy. There's no evil master plan here.

By the way, regarding the search page you mentioned in https://twitter.com/wmhilton/status/853313980760281088, this wasn't build by Facebook. It was actually built by someone at Algolia and they control all the infra that powers it: https://discourse.algolia.com/t/2016-algolia-community-gift-yarn-package-search/319.

> then sure I'd be glad to help release the lockfile parser as its own package! 

Feel free to help, of course 😃 One of the ideas is to use Yarn's "workspaces" feature (https://github.com/yarnpkg/yarn/issues/3294) to handle it. @bestander or @BYK  can probably point you in the right direction if you'd like to help out with this.

>  Lately, I've been playing with SystemJS (specifically the bundled version in getlibs.com) and it's an amazing developer experience. 

This does look pretty interesting, for prototyping at least... How do you go from development to production environment though? It seems like you'd still need to configure a bundler like Webpack for prod. If that's the case, you end up with a very different environment in dev compared to prod, which can be quite problematic as you end up with weird issues that exist in prod but not in dev, and vice versa.

> Yarn doesn't work in the browser 

This would be interesting, although it seems tricky with no filesystem 😛

**Comment by billiegoose** [comment]
> There's no evil master plan here.

Everyone assumes that a master plan has to be evil. It's not black and white like that. I'm a huge fan of Chrome and Android, even though they are both ultimately instruments to direct more traffic to Google's ads and subscription services. Competition helps propel ecosystems forward.

Chrome is actually a good analogy. Firefox already existed... and when Google came out with Chrome they took away a big chunk of Firefox's userbase (including myself). Chrome became the technological leader, and now Firefox has adopted Chrome's Add-on model and deprecate their XUL extensions (probably a good thing TBH). One big difference between the Google/Mozilla competition and Facebook/npm though is that Google already provided a ton of financial backing to Mozilla through buying the right to be the default search engine. Admittedly I haven't looked too deeply into it, but I'm pretty sure I would have heard if Facebook, say, was an npm enterprise customer. I just don't want Facebook to squash npm, inc before it has time to grow into a Mozilla. And I particularly don't want to see it happen as a result of FUD. Or worse, a casualty of unintentional accidental FUD.

(FTR I'm not entirely thrilled with npm, inc's behavior either. I'd love to see them open-source their website again and have a real API again.)

> It seems like you'd still need to configure a bundler like Webpack for prod. If that's the case, you end up with a very different environment in dev compared to prod, which can be quite problematic as you end up with weird issues that exist in prod but not in dev, and vice versa.

SystemJS has a bundler (I haven't tried it yet) and... I find it your argument against bundlers interesting given that `yarn` is bundled with Webpack. I'd be interested in what weird issues you've seen come up. I love/hate weird issues. Oh! And SystemJS has some newfangled alternative to bundling. They've got some crazy HTTP/2 push manifest technology that lets you stream all the dependencies together but load them as individual files, which has the potential to be just as fast (I think) in production as a bundled solution, while still having identical code paths and the dynamic module loading behavior used during development. Definitely an area to watch!

> This would be interesting, although it seems tricky with no filesystem 😛

But what is a filesystem, except [the API exposed by the 'fs' module](https://github.com/jvilk/BrowserFS)? 😀 Since not everything works with SystemJS currently (*cough* recursive dependencies *cough*) I'm working on a way to support traditional `node_modules/` style technology in the browser. Not quite as magical as just `require("foo")` but still, being able to run `npm.install("foo")` in the JS console and have it installed to IndexedDB would be pretty cool. Main obstacle is the tendency for package managers to enthusiastically use Node core modules like `child_process` and `stdin`.

**Comment by Haroenv** [comment]
Hey, just a quick comment here from someone at Algolia. 

The search experience was, as Daniel mentioned, a gift from us to not only everyone using Yarn, but also everyone using npm, since the data is exactly the same. 

We actually suggested this search experience to npm first, but after we submitted the pull request, they moved their repository from public to closed, and coincidentally then chose `npms` to deal with it. 

We decided we still wanted our search and use it to find packages on npm, so we found Yarn a great moment to try that again, and spent some time in making it a complete experience with detail pages etc. 

If you have any questions about that, you can always contact us. 

We have analytics on the search queries, but they are anonymised, and only for reviewing relevancy in the results. It looks like this: 

![analytics](https://user-images.githubusercontent.com/6270048/28709936-8d742d06-7382-11e7-91a6-17705369ab1b.png)
![infra](https://user-images.githubusercontent.com/6270048/28709935-8d732424-7382-11e7-83e6-77d4c02e6e15.png)

**Comment by billiegoose** [comment]
@Haroenv aaawww that's so nice of you! Sorry your PR didn't make it into npm, and super glad it found a home in yarn! It's actually a *really* nice search experience... so nice I was concerned the goal of Yarn had expanded from being the best package manager to crushing the competition. An honest (albeit paranoid super-cynical) mistake. Obviously there's a marketing/PR slant too, but it's a very unobnoxious "Search by Algolia" link at the bottom so even by my suspicious standards it's tasteful.

**Comment by Haroenv** [comment]
Thanks @wmhilton (and sorry for derailing the discussion here) 

By the way, the person who should get the praise for the npm version is @vvo, who also made the initial version of the Yarn search.

**Comment by billiegoose** [comment]
For those interested I've opened a PR in the yarn repo to nudge this idea forward. https://github.com/yarnpkg/yarn/pull/4114

**Comment by billiegoose** [comment]
@scinos We are getting close to having an official lockfile package! See https://github.com/yarnpkg/yarn/pull/4114

**Comment by Daniel15** [comment]
New official lockfile package has been published: https://yarn.pm/@yarnpkg/lockfile. Huge thanks for the help, @wmhilton!

**Comment by billiegoose** [comment]
I'll update my module this afternoon! I think I'll add a deprecation message.

**Comment by billiegoose** [comment]
It's official! Case closed!
